lolesports:
  url: https://esports-api.lolesports.com/persisted/gw/
  language: en-US
  x-api-key: 0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z

leagueoflegends:
  ddragon:
    url: https://ddragon.leagueoflegends.com/cdn/{patch-version}/data/{language-nation}/{component}.json
    patch-version: 11.13.1
    language: en_US
    champion: champion
    item: item
    rune: runesReforged

gamepedia:
  url: https://lol.gamepedia.com/{league}/{tournament}/{component}
  tournament: 2021_Season/Summer_Season
  match-history: Match_History


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# log properties
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace