lolesports:
  url: https://esports-api.lolesports.com/persisted/gw/
  language: en-US
  x-api-key: 0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# log properties
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace