lolesports:
  url: https://esports-api.lolesports.com/persisted/gw/
  language: en-US
  x-api-key: 0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z

feed-lolesports:
  url: https://feed.lolesports.com/livestats/v1

leagueoflegends:
  ddragon:
    url: https://ddragon.leagueoflegends.com/cdn/{patch-version}/data/{language-nation}/{component}.json
    patch-version: 11.13.1  # Set patch version
    language: en_US # Set language code
    champion: champion
    item: item
    rune: runesReforged
  acs:
    url: https://acs.leagueoflegends.com/v1/stats/game
    link: http://matchhistory.na.leagueoflegends.com/en/#match-details
    cookie: id_token={id_token} # Set extracted id_token from leagueoflegends.com

gamepedia:
  url: https://lol.gamepedia.com/{league}/{tournament}/{component}
  tournament: 2021_Season/Summer_Season # Tournament Season
  match-history: Match_History


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://lolesport.cgcrmk7vdleu.ap-northeast-2.rds.amazonaws.com:3306/lolesports
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin #lolesports
    password: aktmxj12! #lol2012
  redis:
    host: 3.36.165.58
    port: 6379
# log properties
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
